export const CONFIG = {
  ENVIRONMENT: process.env.REACT_APP_ENVIRONMENT,
  API_URL: process.env.REACT_APP_API_URL,
  REPOSITORY_URL: process.env.REACT_APP_REPOSITORY_URL,
  BRANCH: process.env.REACT_APP_BRANCH,
  PULL_REQUEST: process.env.REACT_APP_PULL_REQUEST,
  HEAD: process.env.REACT_APP_HEAD,
  COMMIT_REF: process.env.REACT_APP_COMMIT_REF,
  CONTEXT: process.env.REACT_APP_CONTEXT,
  URL: process.env.REACT_APP_URL,
  DEPLOY_URL: process.env.REACT_APP_DEPLOY_URL,
  DEPLOY_PRIME_URL: process.env.REACT_APP_DEPLOY_PRIME_URL,
};
