# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
publish = "build"

# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  command = "npm run build:staging"
  REACT_APP_ENVIRONMENT = "review"
  REACT_APP_API_URL="https://graphql.staging.cogito.study/"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.development.environment]
  command = "npm run build:staging"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_API_URL="https://graphql.staging.cogito.study/"
