# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
publish = "build"

# Production context: all deploys from the Production branch set in your site's
# deploy settings will inherit these settings.
[context.production.environment]
  command = "npm run build"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_API_URL = "https://api.cogito.study/graphql"

# Deploy Preview context: all deploys resulting from a pull/merge request will
# inherit these settings.
[context.deploy-preview.environment]
  command = "npm run build:staging"
  REACT_APP_ENVIRONMENT = "review"
  REACT_APP_API_URL="https://staging.api.cogito.study/graphql"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.development.environment]
  command = "npm run build:staging"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_API_URL="https://staging.api.cogito.study/graphql"